### ISSUE TITLE
Nextcloud 26 Support

### ISSUE THREAD

**Issue by EmJotGeh** [CarnetApp/CarnetNextcloud#204]
Please add the Support for Nextcloud 26.

**Comment by DiWa51** [comment]
You can still enable the app from the Admin interface.
You might need to change max-version in apps/carnet/appinfo/info.xml
`<nextcloud min-version="13" max-version="26"/>`

_(no clue if Nextcloud 26 API changes have impact on the app though :sweat_smile: )_

**Comment by ORSITSupport** [comment]
It worked perfectly, thanks! (with no change of max-version nedeed)

**Comment by demuxer86** [comment]
I'm too afraid to use it.  I got errors in NC25 occasionally.   It's sad because Carnett is by far, leaps and bounds, the best note app for Nextcloud.   The official nextcloud notes app works fine on a PC, but it does not work well at all on Android.  Even in an Android web browser, going to the NC web interface, it doesn't work well.   It's very frustrating.  Carnett worked exactly like Google Keep, which is perfect.

**Comment by PhieF** [comment]
I'm coming back for new nextcloud versions

Le 28 mai 2023 16:27:08 GMT+02:00, demuxer86 ***@***.***> a écrit :

**Comment by demuxer86** [comment]
Are you the developer?!!   Want me to help try to raise some money?

> I'm coming back for new nextcloud versions Le 28 mai 2023 16:27:08 GMT+02:00, demuxer86 ***@***.***>

**Comment by PhieF** [comment]
Yes i'm the dev, i don't need money don't worry but that's really nice !

Le 28 mai 2023 20:06:31 GMT+02:00, demuxer86 ***@***.***> a écrit :

**Comment by demuxer86** [comment]
It's just the best... I would gladly help bring it back to a reliable state if there was any way I could.   Right now I am using Deck because it's the only Nextcloud note app that checks all the boxes for function... works on android well, allows picture uploads, and is reliable.    The bad part is the ui is terrible... it takes a learning curve to get used to it and even then, it's annoying.

**Comment by PhieF** [comment]
> It's just the best... I would gladly help bring it back to a reliable state if there was any way I could. Right now I am using Deck because it's the only Nextcloud note app that checks all the boxes for function... works on android well, allows picture uploads, and is reliable. The bad part is the ui is terrible... it takes a learning curve to get used to it and even then, it's annoying.

One day if I can get back to fully dev it, I'd like to improve the UI with people wanting to use it



I've release the new version for NC 26. It took time because I was on the next version of Carnet, with a markdown editor, and it's still not ready
