### ISSUE TITLE
New release missing

### ISSUE THREAD

**Issue by Drachenkaetzchen** [CarnetApp/CarnetNextcloud#217]
Hi,

the latest release is unfortunately from August. I tried to build it myself, but the Makefile seems to be broken/outdated and the readme references documents which do not exist anymore.

Is there any change you can create a new release?

Thank you!
Felicia

**Comment by PhieF** [comment]
Hi !

@Drachenkaetzchen Release is coming today, I had some bugs but it was due to my dev environment... 

If you are interested in dev in Carnet, I guess indeed the makefile is not useful anymore, and documentation is a mess but I'm trying to write a script for easy dev environment setup here:

https://github.com/CarnetApp/CarnetDocumentation

**Comment by PhieF** [comment]
for now I(m closing since it was released yesterday, feel free to reopen in case of issues with that :)
